service: my-express-application

provider:
  name: aws
  runtime: nodejs20.x
  architecture: arm64
  stage: dev
  region: ap-south-1

functions:
  app:
    handler: dist/index.handler
    timeout: 30
    events:
      - http:
          path: /
          method: any
      - http:
          path: /{proxy+}
          method: any
    environment:
      CLOUDINARY_API_KEY: "834193434524485"
      CLOUDINARY_API_SECRET: "L5PfN8BiLLzPct22b7v_jlp6tYo"
      CLOUDINARY_CLOUD_NAME: "dzp1bui62"
      CORS_ORIGINS: "http://localhost:4001"
      JWT_SECRET: "secret-key"
      MONGO_URI: "mongodb+srv://vijaycha:Admin%40123@cluster0.oriuw1i.mongodb.net/FoodDelivery"

plugins:
  - serverless-offline
